import React from 'react';

const Productdetail = [
    {
        /* Пазлы */
        id: 1,
        Title: "Puzzle Sea Inhabitants",
        Cat: 'Puzzles',
        Price: "$23",
        PriceTotal: "$23",
        Count: 1,
        Manufacturer: "USA",
        Img: './online_toy_store_app/images/puzzles/пазлы1.png',
    },
    {
        id: 2,
        Title: "Puzzle Farm",
        Cat: 'Puzzles',
        Price: "$30",
        PriceTotal: "$30",
        Count: 1,
        Manufacturer: "USA",
        Img: './online_toy_store_app/images/puzzles/пазлы2.png',
    },
    {
        id: 3,
        Title: "Barboskiny Puzzle",
        Cat: 'Puzzles',
        Manufacturer: "USA",
        Price: "$40",
        PriceTotal: "$40",
        Count: 1,
        Img: './online_toy_store_app/images/puzzles/пазлы3.png',
    },
    {
        id: 4,
        Title: "Puzzle Burenka Dasha",
        Cat: 'Puzzles',
        Manufacturer: "USA",
        Price: "$42",
        PriceTotal: "$42",
        Count: 1,
        Img: './online_toy_store_app/images/puzzles/пазлы4.png',
    },
    {
        id: 5,
        Title: "Puzzle Three cats",
        Cat: 'Puzzles',
        Manufacturer: "USA",
        Price: "$12",
        PriceTotal: "$12",
        Count: 1,
        Img: './online_toy_store_app/images/puzzles/пазлы6.png',
    },
    {
        id: 6,
        Title: "Puzzle Three Little pigs",
        Cat: 'Puzzles',
        Manufacturer: "USA",
        Price: "$22",
        Img: './online_toy_store_app/images/puzzles/пазлы7.png',
    },
    {
        id: 7,
        Title: "Puzzle Animals",
        Cat: 'Puzzles',
        Manufacturer: "USA",
        Price: "$22",
        PriceTotal: "$22",
        Count: 1,
        Img: './online_toy_store_app/images/puzzles/пазлы8.png',
    },
    {
        id: 8,
        Title: "Smeshariki Puzzle",
        Cat: 'Puzzles',
        Price: "$22",
        PriceTotal: "$22",
        Count: 1,
        Manufacturer: "USA",
        Img: './online_toy_store_app/images/puzzles/пазлы9.png',
    },
    {
        id: 9,
        Title: "Puzzle red car",
        Cat: 'Puzzles',
        Manufacturer: "China",
        Price: "$22",
        PriceTotal: "$22",
        Count: 1,
        Img: './online_toy_store_app/images/puzzles/пазлы10.png',
    },
    /* Плюшевые игрушки */
    {
        id: 10,
        Title: "Plush toy Teddy bear with a bow",
        Cat: 'Plush',
        Manufacturer: "China",
        Price: "$52",
        PriceTotal: "$52",
        Count: 1,
        Img: './online_toy_store_app/images/plushes/plush-1.png',
    },
    {
        id: 11,
        Title: "Cute Lion With Big Eyes",
        Cat: 'Plush',
        Price: "$45",
        PriceTotal: "$45",
        Count: 1,
        Manufacturer: "China",
        Img: './online_toy_store_app/images/plushes/plush-2.png',
    },
    /* машины*/
    {
        id: 12,
        Title: "Green Car",
        Cat: 'Cars',
        Manufacturer: "China",
        Price: "$55",
        PriceTotal: "$55",
        Count: 1,
        Img: './online_toy_store_app/images/cars/машина1.png',
    },
    {
        id: 13,
        Title: "Red Sport Car",
        Cat: 'Cars',
        Price: "$79",
        PriceTotal: "$79",
        Count: 1,
        Manufacturer: "China",
        Img: './online_toy_store_app/images/cars/машина5.png',
    },
    {
        id: 14,
        Title: "Car Truck Yellow",
        Cat: 'Cars',
        Manufacturer: "China",
        Price: "$55",
        PriceTotal: "$55",
        Count: 1,
        Img: './online_toy_store_app/images/cars/машина3.png',
    },
    /*meccano */
    {
        id: 15,
        Title: "Robot",
        Cat: 'Meccano',
        Manufacturer: "China",
        Price: "$65",
        PriceTotal: "$65",
        Count: 1,
        Img: './online_toy_store_app/images/meccano/meccano-1.png',
    },
    {
        id: 16,
        Title: "Yellow Transformer",
        Cat: 'Meccano',
        Price: "$89",
        PriceTotal: "$89",
        Count: 1,
        Manufacturer: "China",
        Img: './online_toy_store_app/images/meccano/meccano-2.png',
    },
    /* Куклы */
    {
        id: 17,
        Title: "Doll Aurora",
        Cat: 'Dolls',
        Price: "$75",
        PriceTotal: "$75",
        Count: 1,
        Manufacturer: "China",
        Img: './online_toy_store_app/images/dolls/doll5.png',
    },
    {
        id: 18,
        Title: "Rapunzel",
        Cat: 'Dolls',
        Price: "$85",
        PriceTotal: "$85",
        Count: 1,
        Manufacturer: "USA",
        Img: './online_toy_store_app/images/dolls/doll6.png',
    },
    {
        id: 19,
        Title: "Barbie Doll",
        Cat: 'Dolls',
        Manufacturer: "USA",
        Price: "$65",
        PriceTotal: "$65",
        Count: 1,
        Img: './online_toy_store_app/images/dolls/doll1.png',
    },
    {
        id: 20,
        Title: "Barbie Doll in beautiful dress",
        Cat: 'Dolls',
        Manufacturer: "USA",
        Price: "$100",
        PriceTotal: "$100",
        Count: 1,
        Img: './online_toy_store_app/images/dolls/doll2.png',
    },
    {
        id: 21,
        Title: "Barbie Doll Fairy",
        Cat: 'Dolls',
        Manufacturer: "USA",
        Price: "$75",
        PriceTotal: "$75",
        Count: 1,
        Img: './online_toy_store_app/images/dolls/doll3.png',
    },
    {
        id: 22,
        Title: "Doll Elsa",
        Cat: 'Dolls',
        Price: "$75",
        PriceTotal: "$75",
        Count: 1,
        Manufacturer: "USA",
        Img: './online_toy_store_app/images/dolls/doll4.png',
    },
    /* доп. meccano*/
    {
        id: 23,
        Title: "White Robot-Dog",
        Cat: 'Meccano',
        Price: "$199",
        PriceTotal: "$199",
        Count: 1,
        Manufacturer: "China",
        Img: './online_toy_store_app/images/meccano/meccano-3.png',
    },
    {
        id: 24,
        Title: "White Robot",
        Cat: 'Meccano',
        Price: "$299",
        PriceTotal: "$299",
        Count: 1,
        Manufacturer: "China",
        Img: './online_toy_store_app/images/meccano/meccano-4.png',
    },
    {
        id: 25,
        Title: "Sapphirine Robot",
        Cat: 'Meccano',
        Price: "$99",
        PriceTotal: "$99",
        Count: 1,
        Manufacturer: "China",
        Img: './online_toy_store_app/images/meccano/meccano-5.png',
    },
    /* доп. plushes*/
    {
        id: 26,
        Title: "Cute cat",
        Cat: 'Plush',
        Price: "$79",
        PriceTotal: "$79",
        Count: 1,
        Manufacturer: "China",
        Img: './online_toy_store_app/images/plushes/plush-3.png',
    },
    {
        id: 27,
        Title: "Big fluffy cat",
        Cat: 'Plush',
        Price: "$59",
        PriceTotal: "$59",
        Count: 1,
        Manufacturer: "China",
        Img: './online_toy_store_app/images/plushes/plush-4.png',
    },
    {
        id: 28,
        Title: "Cute grey raccoon",
        Cat: 'Plush',
        Price: "$44",
        PriceTotal: "$44",
        Count: 1,
        Manufacturer: "China",
        Img: './online_toy_store_app/images/plushes/plush-5.png',
    },
    /* доп. cars*/
    {
        id: 29,
        Title: "White Sport Car",
        Cat: 'Cars',
        Price: "$99",
        PriceTotal: "$99",
        Count: 1,
        Manufacturer: "China",
        Img: './online_toy_store_app/images/cars/машина4.png',
    }, 
    {
        id: 30,
        Title: "White Rabbit",
        Cat: 'Plush',
        Price: "$99",
        PriceTotal: "$99",
        Count: 1,
        Manufacturer: "China",
        Img: './online_toy_store_app/images/plushes/plush-7.png',
    }, 
];

export default Productdetail;